version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: chat-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatgpt
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: chat-adminer
    restart: always
    ports:
      - "8080:8080"
